//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17379
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/CleverDogStudios.FormulaOnePickr.WebServi" +
        "ce")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="FormulaOnePickrService.IFormulaOnePickrService")]
    public interface IFormulaOnePickrService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormulaOnePickrService/GetDrivers", ReplyAction="http://tempuri.org/IFormulaOnePickrService/GetDriversResponse")]
        string GetDrivers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFormulaOnePickrService/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IFormulaOnePickrService/GetDataUsingDataContractResponse")]
        CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.CompositeType GetDataUsingDataContract(CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFormulaOnePickrServiceChannel : CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.IFormulaOnePickrService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FormulaOnePickrServiceClient : System.ServiceModel.ClientBase<CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.IFormulaOnePickrService>, CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.IFormulaOnePickrService {
        
        public FormulaOnePickrServiceClient() {
        }
        
        public FormulaOnePickrServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FormulaOnePickrServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormulaOnePickrServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FormulaOnePickrServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetDrivers() {
            return base.Channel.GetDrivers();
        }
        
        public CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.CompositeType GetDataUsingDataContract(CleverDogStudios.FormulaOnePickr.Web.FormulaOnePickrService.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
    }
}
